apiVersion: batch/v1
kind: Job
metadata:
  name: httperf-load
spec:
  parallelism: 1
  template:
    spec:
      containers:
        - name: httperf-load
          imagePullPolicy: Always
          image: skonto/httperf
          args:
            - /bin/sh
            - -c
            - 'httperf --server sensor-agent.default.svc --uri="/" --port 80  --rate 100 --timeout 1 --method POST --add-header "Accept: application/json\nContent-Type: application/json\n" --wsesslog=10000,0,perf.txt'
          resources:
            requests:
              memory: "64Mi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
          securityContext:
            allowPrivilegeEscalation: true
      restartPolicy: Never